### ISSUE TITLE
Test failures with Ruby2.7

### ISSUE THREAD

**Issue by utkarsh2102** [dejan/espeak-ruby#13]
Hi,

There are following test failures with Ruby 2.7:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│ Run tests for ruby2.7 from debian/ruby-tests.rake                            │
└──────────────────────────────────────────────────────────────────────────────┘

RUBYLIB=. GEM_PATH=/home/utkarsh/debian/ruby-team/espeak/ruby-espeak/debian/ruby-espeak/usr/share/rubygems-integration/all:/home/utkarsh/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0 ruby2.7 -S rake -f debian/ruby-tests.rake
/usr/bin/ruby2.7 -w -I"test"  "/usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/rake_test_loader.rb" "test/cases/speech_test.rb" "test/cases/voice_test.rb" "test/test_helper.rb" -v
Loaded suite /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/rake_test_loader
Started
SpeechTest: 
  test_save:				.: (0.022006)
VoiceTest: 
  test_all:				F
===============================================================
     11:   def test_all
     12:     all_voices = Voice.all
     13:     assert all_voices.size > 0
  => 14:     assert %w(M F).include?(all_voices.first.gender)
     15:   end
     16: 
     17:   def test_find_by_language
/home/utkarsh/debian/ruby-team/espeak/ruby-espeak/test/cases/voice_test.rb:14:in `test_all'
Failure: test_all(VoiceTest): <false> is not true.
===============================================================
: (0.028455)
  test_find_by_language:		E
===============================================================
     16: 
     17:   def test_find_by_language
     18:     voice = Voice.find_by_language('en')
  => 19:     assert_equal 'en', voice.language
     20:   end
     21: end
/home/utkarsh/debian/ruby-team/espeak/ruby-espeak/test/cases/voice_test.rb:19:in `test_find_by_language'
Error: test_find_by_language(VoiceTest): NoMethodError: undefined method `language' for nil:NilClass
===============================================================
: (0.004145)

Finished in 0.055004519 seconds.
---------------------------------------------------------------
3 tests, 4 assertions, 1 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
33.3333% passed
---------------------------------------------------------------
54.54 tests/s, 72.72 assertions/s
rake aborted!
Command failed with status (1): [ruby -w -I"test"  "/usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/rake_test_loader.rb" "test/cases/speech_test.rb" "test/cases/voice_test.rb" "test/test_helper.rb" -v]
/usr/share/rubygems-integration/all/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)
ERROR: Test "ruby2.7" failed. Exiting.
```

Any clue on how to fix this?

**Comment by dejan** [comment]
Actually the problem was that `espeak --voices` changed the output format slightly. This is addressed in https://github.com/dejan/espeak-ruby/pull/14
