### ISSUE TITLE
Cannot load such file

### ISSUE THREAD

**Issue by y2kstack** [dejan/espeak-ruby#24]
/Users/raven_hacks/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/espeak-ruby-1.1.0/lib/espeak/voice.rb:17:in `popen': No such file or directory - espeak (Errno::ENOENT)
        from /Users/raven_hacks/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/espeak-ruby-1.1.0/lib/espeak/voice.rb:17:in `all'
        from /Users/raven_hacks/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/espeak-ruby-1.1.0/lib/espeak.rb:8:in `<top (required)>'
        from <internal:/Users/raven_hacks/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/Users/raven_hacks/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/Users/raven_hacks/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from epseak.rb:1:in `<main>'
<internal:/Users/raven_hacks/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- espeak (LoadError)
        from <internal:/Users/raven_hacks/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from epseak.rb:1:in `<main>'

**Comment by y2kstack** [comment]
First we need to install dependency to use this got it thanks
